### ISSUE TITLE
Gdzie jest język polski gościu dodaj to

### ISSUE THREAD

**Issue by Synnek7337** [zneix/zneixbot#5]
zapraszam na moje nowe repo [redacted]

**Comment by Synnek7337** [comment]
**FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE FEATURE ABUSE**

**Comment by Synnek7337** [comment]
https://cdn.discordapp.com/attachments/597840229541347351/685956203641176083/a_i_jeszcze_jedno.png

**Comment by zneix** [comment]
Język Polski zostanie dodany jak tylko wymyślę w jaki sposób będzie to działać

**Comment by Synnek7337** [comment]
zneix to gej
